1.Task: Create a matrix of zeros with shape (4, 3) (4 rows, 3 columns). Then, print its shape and data type.

In [13]:
import numpy as np
weights=np.zeros([4,3])
print(weights)
print(weights.shape) #shape of matrix
print(weights.dtype)  #datatype of matrix elememts
print(weights.ndim) # dimension of array
print(weights.size) # size of matix (count of elements)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
(4, 3)
float64
2
12


2.You have a flat list of 12 numbers. You need to feed it into a Neural Network that expects a specific grid.

Task: Create an array of numbers from 0 to 11 (Hint: np.arange). Reshape it into a matrix with 4 Rows and 3 Columns.

Why: Neural Nets are picky. You constantly reshape data to fit layers.

In [29]:

a=np.arange(12)
a=a.reshape(4,3)
print(a)
b=np.arange(0,13,3)#first_arg = min_val,second_arg=max_val,third_arg=step size
print(b)
b=b.reshape(1,5)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[ 0  3  6  9 12]


###3. Create a matrix A of ones with shape (3, 3).Create a vector b = [1, 2, 3].Add them: A + b.Crucial Step: Now try to add them as columns! Create a vector c = [1, 2, 3] but reshape it so it adds vertically to A.Why: Adding Bias terms ($y = mx + c$) relies entirely on this.

In [46]:
a=np.zeros([3,3])
print('Matrix a')
print(a)

b=(1,2,3)
#print(b)
print('matrix a+b')
c=a+b
print(c)
d=(1,2,3)
d=np.reshape(d,[3,1])
#print(d)
print('matrix a+d')
e=a+d
print(e)

Matrix a
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
matrix a+b
[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]
matrix a+d
[[1. 1. 1.]
 [2. 2. 2.]
 [3. 3. 3.]]


4.Create matrix X with shape (2, 3).

Create matrix Y with shape (3, 2).

Multiply them (np.dot). What is the shape of the result?

Bonus: Try multiplying Y and X (reverse order). Does it work? What is the shape?

Why: The order of multiplication changes the output dimensions. This creates "Silent Bugs."

In [59]:
x=np.arange(6)
x=np.reshape(x,[2,3])
print('Matrix X')
print(x)

y=np.arange(6,12)
y=np.reshape(y,[3,2])
print('Matrix Y')
print(y)

print('x dot y')
w=np.dot(x,y)
print(w)
print(w.shape)

print('y dot x')
u=np.dot(y,x)
print(u)
print(u.shape)

Matrix X
[[0 1 2]
 [3 4 5]]
Matrix Y
[[ 6  7]
 [ 8  9]
 [10 11]]
x dot y
[[ 28  31]
 [100 112]]
(2, 2)
y dot x
[[21 34 47]
 [27 44 61]
 [33 54 75]]
(3, 3)


5.The "Filter" (ReLU Manual Mode)

Create a random array with negative numbers: arr = np.array([10, -5, 2, -1]).

The Task: Use Boolean Masking (square brackets []) to set all negative numbers to 0.

Hint: arr[arr < 0] selects the specific numbers. Can you assign 0 to them?

In [64]:
'''arr = np.array([10, -5, 2, -1])
print(arr)

for i in range (len(arr)):
    if(arr[i]<0):
        arr[i]=0

print(arr)'''

#loop takes long so boolean masking is efficient and fast.

arr = np.array([10, -5, 2, -1])

# The "Mask" (True/False check)
# This creates: [False, True, False, True]
mask = arr < 0 

# The "Vectorized" Update
# It says: "Where the mask is True, set value to 0"
arr[mask] = 0 

print(arr)

[10  0  2  0]
