# Matrix multiplication.
# Understanding Usage of multiplication of matrix and it's application.
# Checking for scores of movies

# We take two matrix one for users/viewers WITH 3 genres with user like scores,

# and one for movies with 3 different genres.



In [2]:
import numpy as np

In [24]:
#Cols represent preferences for: `[Action, Comedy, Sci-Fi]`.
#rows represent viewers
users=np.array([
    [1,0,5],
    [0,0,5],
    [2,3,3]]
          )
#Cols represent specific movies: `[GGVV, UK, Kantara]`.
#rows represent generes
movies=np.array([
    [1,1,1],
    [0,0,1],
    [1,0,1]]
           )
res=np.dot(users,movies)
movie_names = ["GGVV", "UK", "Kantara"]

print('GGVV | UK | Kantara')
print(f"{res[0]}")
print(f"{res[1]}")
print(f"{res[2]}")

#3. THE LOGIC: Identify which movies are liked
# We loop through each user to interpret their scores
for i in range(len(res)):
    user_id = i + 1
    user_scores = res[i]
    
    print(f"\n--- Analysis for User {user_id} ---")
    
    # Strategy: Find the highest score (Favorite Movie)
    best_score_index = np.argmax(user_scores) # Returns index of highest number
    favorite_movie = movie_names[best_score_index]
    
    print(f"Favorite Movie: {favorite_movie}")
    
    # Strategy: List all 'Liked' movies (Threshold > 5)
    print("All Liked Movies (Score > 5):")
    for j in range(len(user_scores)):
        if user_scores[j] > 5:
            print(f" - {movie_names[j]} (Score: {user_scores[j]})")

GGVV | UK | Kantara
[6 1 6]
[5 0 5]
[5 2 8]

--- Analysis for User 1 ---
Favorite Movie: GGVV
All Liked Movies (Score > 5):
 - GGVV (Score: 6)
 - Kantara (Score: 6)

--- Analysis for User 2 ---
Favorite Movie: GGVV
All Liked Movies (Score > 5):

--- Analysis for User 3 ---
Favorite Movie: Kantara
All Liked Movies (Score > 5):
 - Kantara (Score: 8)


# Adding "Bias"

## 1. The Concept: Why "+ b"?
In the real world, "Similarity" isn't the only factor.

User Bias: Some users are "Critics" (rate everything lower).
Some are "Optimists" (rate everything higher).

Item Bias: Some movies are just universally popular, regardless of genre.

To model this, we change our equation from linear (y = ax) to affine (y = ax + b).
Final Score = User (dot) Movie + Bias

## 2. The Implementation: Broadcasting
We want to add a specific "Mood Score" to each user.
* **User 0 (Critic):** Subtracts 2 points from *every* movie.
* **User 1 (Optimist):** Adds 2 points to *every* movie.
* **User 2 (Neutral):** Adds 0 points.

**The Broadcasting Challenge:**
* `Scores` Matrix shape: `(3 Users, 3 Movies)`
* `Bias` Vector shape: `(3 Users)`
To add them, we must reshape the Bias vector to `(3, 1)` (Vertical). This forces NumPy to apply the bias **Row-by-Row** (per user) instead of Column-by-Column.

In [22]:
#mood of users
user_bias=np.array([-2,0,1])

user_biass=user_bias.reshape(-1,1)

Res=res+user_biass
print(Res)

# I can use the same logic again to find user and movie analysis

[[ 4 -1  4]
 [ 5  0  5]
 [ 6  3  9]]


When we eventually use PyTorch or TensorFlow, you will see layers defined like Linear(in_features=3, out_features=1, bias=True)

this is the same logic we built from scratch.


# Activation Function (ReLU)

## 1. The Concept
Our linear calculation ($Y = WX + b$) is just math. It can produce values from $-\infty$ to $+\infty$.
But biological neurons don't send "negative signals." They either **Fire** (send a signal) or **Stay Silent** (0).

To mimic this, and to introduce **Non-Linearity** (which allows AI to learn complex patterns), we use an Activation Function.

## 2. The ReLU (Rectified Linear Unit)
It is the most common activation in modern AI (ChatGPT, Computer Vision).
$$f(x) = \max(0, x)$$

* **Input:** `[-2, 5, -8, 10]`
* **Output:** `[ 0, 5,  0, 10]`

In our Recommender:
* Negative scores (Dislikes) become **0** (Ignored).
* Positive scores (Likes) remain **Linear** (Stronger likes = Higher numbers).

In [17]:
# np.maximum compares 0 and the score, picking the larger one.
activated_scores = np.maximum(0, Res)

print("\n--- Final Output after ReLU (Activation) ---")
print(activated_scores)


--- Final Output after ReLU (Activation) ---
[[4 0 4]
 [5 0 5]
 [6 3 9]]


I will put the analysis code again on final output.

In [23]:
# 3. THE LOGIC: Identify which movies are liked
# We loop through each user to interpret their scores
for i in range(len(activated_scores)):
    user_id = i + 1
    user_scores = activated_scores[i]
    
    print(f"\n--- Analysis for User {user_id} ---")
    
    # Strategy: Find the highest score (Favorite Movie)
    best_score_index = np.argmax(user_scores) # Returns index of highest number
    favorite_movie = movie_names[best_score_index]
    
    print(f"Favorite Movie: {favorite_movie}")
    
    # Strategy: List all 'Liked' movies (Threshold > 5)
    print("All Liked Movies (Score > 5):")
    for j in range(len(user_scores)):
        if user_scores[j] > 5:
            print(f" - {movie_names[j]} (Score: {user_scores[j]})")


--- Analysis for User 1 ---
Favorite Movie: GGVV
All Liked Movies (Score > 5):

--- Analysis for User 2 ---
Favorite Movie: GGVV
All Liked Movies (Score > 5):

--- Analysis for User 3 ---
Favorite Movie: Kantara
All Liked Movies (Score > 5):
 - GGVV (Score: 6)
 - Kantara (Score: 9)


Summary 


##Forward Pass:
Definition: Calculating the prediction ($Y$) from the input ($X$).
Math: $Y = \text{Activation}(X \cdot W + b)$Your Code: activated_scores = np.maximum(0, (np.dot(users, movies) + bias))


##Dense Layer:
Definition: A layer of neurons where each neuron receives input from all neurons in the previous layer.Implementation: It is just Matrix Multiplication.Why "Dense"? Because the web of connections is "dense" (full), not sparse (empty)

Gemini Guide.